require("engine/test/bustedhelper")
local adventure = require("story/adventure")

describe('adventure', function ()

  describe('_init', function ()
    it('should init a adventure', function ()
      local a = adventure()
      assert.is_not_nil(a)
    end)
  end)

  describe('on_enter', function ()
    it('should not error', function ()
      local a = adventure()
      assert.has_no_errors(function ()
        a:on_enter()
      end)
    end)
  end)

  describe('on_exit', function ()
    it('should not error', function ()
      local a = adventure()
      assert.has_no_errors(function ()
        a:on_exit()
      end)
    end)
  end)

  describe('update', function ()
    it('should not error', function ()
      local a = adventure()
      assert.has_no_errors(function ()
        a:on_exit()
      end)
    end)
  end)

  describe('render', function ()
    it('should not error', function ()
      local a = adventure()
      assert.has_no_errors(function ()
        a:render()
      end)
    end)
  end)

end)
